sudo: required
language: generic
dist: focal

services:
  - docker

matrix:
  include:
    - name: "Focal Fossa Nightly PCL"
      env: ROS_DISTRO=focal
    - name: "Focal Fossa Nightly PCL with CUDA"
      env: ROS_DISTRO=focal_cuda
    - name: "Focal Fossa noetic"
      env: ROS_DISTRO=noetic
    - name: "Focal Fossa noetic_llvm"
      env: ROS_DISTRO=noetic_llvm
    - name: "Bionic melodic_llvm"
      env: ROS_DISTRO=melodic_llvm
    - name: "Bionic melodic"
      env: ROS_DISTRO=melodic

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin || true
  - docker build -f ./docker/$ROS_DISTRO/Dockerfile .

env:
  global:
  - secure: "mVtiFoHyfQo+ty8T99uwADqBrU7Ex+Vn1U1a215RWEe5mZg1udvC7hl1lDkkGsDej9NW3vyZJqSyimq9OKqPb1Qe02bPP0FoOIA0IZzDAMEpWgQlUzwZGxrG4iTLv1O3gJJ+bgqBJyvy6RpH4KSXTuVRuuO38z4F4fkBR2gfqDiWh+cgx6xqBZnYewNW9ob3OqEw0tjxDtsyU4XLhK7u6Y4pIfkomH1jAQJxtNaMhMGqXTyasltqw3RP2LSbj7Lwv4IE//VDoi/rEQAqf3V8MIBzCsyX+je8zo30hy2fm1ioGqUDgdig45OTqD/G2UGuGFAV0SfVLFdCrDEdm7Wm3e2oWvFm1oB9dvq2zg4Re5xUwygi6ogqnEZnJJEOz3YYMGqjUnbTsysiyRfjwMm0PKDeQet+Fu02u09zdat3cy6QOsQz4CtPaz17jvSAyhqhnciG2TDpZb0CPuGHAlo7n+oe8KrcK68DDQbso3vNbSg+qxKaZXfJOR3jhAbT8nSVxX7yQ72FhWGPjJv4fjAXoSZiNx/pv2lI5GWUmL4fNkj70sh2KpC8mGjT8CpGVgSRhJGaYR5YJIDrEgkwe7VhOnYSg69WJ9ywK41ndOiHyyknS+K0yUqW4jelv2XdMJiTonfRZApGVHCv7PhS5NPKd4rkPItoZAOLk5DnsPapf+M="
  - secure: "iKV5UtmQh1jxumupMe71mZ9uGlRNLgfj/V1h3SDKuMNbU2Wd6YUXX256VQmHSWGLCPJwP5z4ZsvUQTDO5pq9LnZ1Xa1EB02bDQzDjNvXNx5zWflDJz2Oq0PzRc7AY+PZv7Id85v1kO6zF0dFI6Xd9u/ztZK/HF6u+82+gRVgM/tdgEZ8lfhb7nK8Bz4G7jENr4buknY6iRU59/AAJH5dTBVDDopWCYP35dkycCSZXGYuascNh7Dwp8sKgIV/0932Qj+xL/+bI8d+4PnRaTBhvgp57oTqkp7GHRn36ZO82eigiv2AsAPWIe772b5H5l3FL9/qJjNE+SB6v67lNtSbMXcXsLQtSNqJHZXKAdMhVlZfW7uc1UiVFHq3KuZT4412oWb4Uw31SI5vj5cCGIQSHtH+TuYA9lVCzkZzQMB3pB0eBuMD+8Bh8jLosZ2OUM786KLBSAsmyuDTEJ6QBhx+3+s106vGWiCUKoCl55OAhN/YVCZ2ZrjFM4YdIYQLVEZ2Yq8shAqh1AlkX69KO3SOLE0vqd+MYisxs8JS0mSmSlfennFhw63A/B8qT6/deYgCbJ4qd5l7RHlaZyLgBBLmCDxrmtB1HSw3phIDxO1ezB/Noe4MXwwWD17hH24EiaJQ2c9RDhuMBYSrHxh1ZUFt2K71Ylbg2iv93G2ZnwBkJX8="
